### ISSUE TITLE
Explanation of rendering data

### ISSUE THREAD

**Issue by yilei0620** [chrischoy/3D-R2N2#12]
Dear Author,

I downloaded rendering image dataset. Can you give a simple explanation about the meaning of each lines in file  _rendering_metadata.txt_ ?

Thank you so much.

**Comment by chrischoy** [comment]
From the left, they are azimuth, elevation, in-plane rotation, distance, the field of view.

**Comment by myprospection** [comment]
> From the left, they are azimuth, elevation, in-plane rotation, distance, the field of view.
What is the unit of distance?
