### ISSUE TITLE
Data Loading & Memory Issue

### ISSUE THREAD

**Issue by abbhinavvenkat** [chrischoy/3D-R2N2#13]
Hi,

I have been testing the R2N2 on my custom dataset. I have got a few memory allocation errors on a 12GB Titan X. It appears as though the whole of the dataset gets loaded into the GPU memory and is then split into batches. Can you confirm if this is the case? As I am new to Theano, I don't see it being done explicitly, hence, it is just an intuition. If not, what could be the other causes for a memory allocation issue with this architecture? I have full access to the 12GB of GPU memory with 64 GB of RAM.  
As I am using a batch size of 5, ideally, I shouldn't be facing any issues, because, as per the paper, it has been trained with a batch size of 24. 

Thanks.

P.S : Link to the error: https://pastebin.com/FJy11p3s

**Comment by chrischoy** [comment]
The data is not loaded to the GPU until it trains on that specific batch.

Data is first loaded on a CPU in a different process using `multiprocessing.Process`. Then it is fed into the [`multiprocessing.Queue`](https://github.com/chrischoy/3D-R2N2/blob/master/lib/data_process.py#L92) which the main process uses to train the network. 

So, the answer is no, we do not load the whole dataset. Please try to use smaller batch_size to make it fit inside a GPU.
