### ISSUE TITLE
ResidualGRUNet TEST

### ISSUE THREAD

**Issue by hangongzi** [chrischoy/3D-R2N2#23]
Hi, I use Ubuntu 16.04 to implement the project and get a good result. And ,When I training the network with the function train_net(), it get a normal result. But ,When I test the network with the function test_net(),I get all of results of mAP are 0. Is it right, and should I change something in your scripts?
Thanks for your answer！

**Comment by hzxie** [comment]
Same here.

**Comment by hzxie** [comment]
In `test_net.py`:

the statement in line 76: `batch_idx += 1` should be executed after `print` in line 78.

**Comment by hzxie** [comment]
Fixed in #28.

![screenshot from 2018-01-08 16-34-21](https://user-images.githubusercontent.com/1730504/34663442-d006585c-f491-11e7-973b-18d211549b46.png)
