### ISSUE TITLE
No such file or directory: 'curl'

### ISSUE THREAD

**Issue by Tony1Q84** [chrischoy/3D-R2N2#32]
Sorry to bother you, I'm new to this, when I run the demo.py, I got this problem, may you please tell me how to fix it ?thank you 
 
Using gpu device 0: GeForce GTX 1050 Ti (CNMeM is disabled, cuDNN 6021)
/home/tony/.local/lib/python3.5/site-packages/theano/sandbox/cuda/__init__.py:600: UserWarning: Your cuDNN version is more recent than the one Theano officially supports. If you see any problems, try updating Theano or downgrading cuDNN to version 5.
  warnings.warn(warn)
Downloading a pretrained model
Traceback (most recent call last):
  File "demo.py", line 84, in <module>
    main()
  File "demo.py", line 55, in main
    download_model(DEFAULT_WEIGHTS)
  File "demo.py", line 34, in download_model
    '--create-dirs', '-o', fn])
  File "/usr/lib/python3.5/subprocess.py", line 557, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'curl'

**Comment by Tony1Q84** [comment]
I have solved the problem, sorry for the trouble that I may bring, thank you!

**Comment by tansinjahan** [comment]
Hi Tony, I am also having the same issue while running demo.py.Could you please tell me how you solved the problem. Thank you.

**Comment by Tony1Q84** [comment]
@tansinjahan Hello, I solve this problem by create a folder named output, and put the trained model into this path (output/ResidualGRUNet/default_model/weights.npy), hope this can solve your peoblem

**Comment by kalki123123** [comment]
@tansinjahan   @Tony1Q84  If you install curl (using sudo apt get in ubuntu), you don't have to create output/ResidualGRUNet/default_model/weights.npy as it will be created once the pre-trained model is downloaded.

**Comment by triple-tam** [comment]
for me this solved the issue on ubuntu 16.04
`sudo apt-get install curl`
maybe this also helps the first command
`sudo apt install libcurl4-openssl-dev libssl-dev`

**Comment by dardaa** [comment]
Hi eveyone, someone know how i can resolve this problem, I'm beginner and I'm bloked.... please i'm waiting yours response and thanks in advance

Can not use cuDNN on context None: cannot compile with cuDNN. We got this error:
b'/tmp/try_flags_unc47ff0.c:4:19: fatal error: cudnn.h: No such file or directory\ncompilation terminated.\n'
Mapped name None to device cuda: GeForce 920MX (0000:01:00.0)
Downloading a pretrained model
You don't have permission to create output/ResidualGRUNet.
/home/phd/3D-R2N2/lib/layers.py:353: UserWarning: DEPRECATION: the 'ds' parameter is not going to exist anymore as it is going to be replaced by the parameter 'ws'.
  padding=self._padding)
/home/phd/3D-R2N2/lib/layers.py:353: UserWarning: DEPRECATION: the 'padding' parameter is not going to exist anymore as it is going to be replaced by the parameter 'pad'.
  padding=self._padding)
loading network parameters from output/ResidualGRUNet/default_model/weights.npy
Traceback (most recent call last):
  File "demo.py", line 84, in <module>
    main()
  File "demo.py", line 62, in main
    net.load(DEFAULT_WEIGHTS)                        # load downloaded weights
  File "/home/phd/3D-R2N2/models/net.py", line 71, in load
    params_cpu_file = np.load(filename)
  File "/home/phd/anaconda3/envs/py3-theano/lib/python3.6/site-packages/numpy/lib/npyio.py", line 422, in load
    fid = open(os_fspath(file), "rb")
PermissionError: [Errno 13] Permission denied: 'output/ResidualGRUNet/default_model/weights.npy'

**Comment by sheikhaafaq** [comment]
close the terminal and try again
