### ISSUE TITLE
Datasets and Pre-trained model is not available

### ISSUE THREAD

**Issue by SummitChen** [chrischoy/3D-R2N2#35]
The links for datasets and pre-trained model are put within the domain of Standford University. Outside people without login username and password cannot access them. Could you please put them in open places?

**Comment by chrischoy** [comment]
Try to use the command line `wget`.

**Comment by qasimz** [comment]
wget is not working as well. I am getting the following error
``
wget ftp://cs.stanford.edu/cs/cvgl/ResidualGRUNet.npy
--2018-04-06 23:40:08--  ftp://cs.stanford.edu/cs/cvgl/ResidualGRUNet.npy
           => ‘ResidualGRUNet.npy’
Resolving cs.stanford.edu (cs.stanford.edu)... 171.64.64.64
Connecting to cs.stanford.edu (cs.stanford.edu)|171.64.64.64|:21... connected.
Logging in as anonymous ... 
Login incorrect.

``

**Comment by DetaiLC** [comment]
I have the same problem, wget is not working either

**Comment by B1ueber2y** [comment]
Hi @chrischoy , 

I am in need of the splited train/test data and your model as a strong baseline. I have the same problem. Could you please share the data in open places?

Thanks a lot!

**Comment by chrischoy** [comment]
Updated the readme file.

Please download the files from 
ShapeNet rendered images [http://cvgl.stanford.edu/data2/ShapeNetRendering.tgz](http://cvgl.stanford.edu/data2/ShapeNetRendering.tgz)
ShapeNet voxelized models [http://cvgl.stanford.edu/data2/ShapeNetVox32.tgz](http://cvgl.stanford.edu/data2/ShapeNetVox32.tgz)
Trained ResidualGRUNet Weights [http://cvgl.stanford.edu/data2/ResidualGRUNet.npy](http://cvgl.stanford.edu/data2/ResidualGRUNet.npy)

**Comment by Jovania** [comment]
Hi @chrischoy 
Could someone please send me an example of the split file (training, testing, validation)?
