### ISSUE TITLE
Can I use the CPU mode to train the network?

### ISSUE THREAD

**Issue by RachelSun** [chrischoy/3D-R2N2#5]
Is it possible to train this model using only CPU. When I use only CPU, it stops and show:
====================
lib/data_io.py: model paths from ./experiments/dataset/shapenet_1000.json
[INFO/ReconstructionDataProcess-1] child process calling self.run()
lib/data_io.py: model paths from ./experiments/dataset/shapenet_1000.json
Set the learning rate to 0.000100.
[INFO/ReconstructionDataProcess-2] child process calling self.run()
Compiling training function
WARNING (theano.tensor.blas): We did not found a dynamic library into the library_dir of the library we use for blas. If you use ATLAS, make sure to compile it with dynamics library.
2017-03-31 09:19:01.570096 Iter: 0 Loss: 0.722025
Compiling testing function

==========================
Does it mean that the training is stopped or the training needs more time?

Thank you very much.

**Comment by chrischoy** [comment]
Theano by default supports CPU as well as GPU.
If you want to use the CPU to train the network, delete the line https://github.com/chrischoy/3D-R2N2/blob/master/main.py#L77. However, the training would be very slow.

There are many GPU cloud platforms including AWS and Google Cloud so I recommend you to look into those if you plan to train the network from scratch.
