### ISSUE TITLE
Error:

### ISSUE THREAD

**Issue by RachelSun** [chrischoy/3D-R2N2#6]

**Comment by RachelSun** [comment]
Hi, When I run the demo, there is an error:  
from theano.tensor.signal import downsample 
ImportError:   cannot import name 'downsample'
Is this because the unmatch version of theano? Thank you.

**Comment by yeliu0218** [comment]
There is a solution [https://github.com/Theano/Theano/issues/4337](url)

In lib/layer.py,  change

from theano.tensor.signal import downsample
...
pooled_out = downsample.max_pool_2d( ... )
to

from theano.tensor.signal import pool
...
pooled_out = pool.pool_2d( ... )

Then it should work

**Comment by chrischoy** [comment]
Resolved #15
