### ISSUE TITLE
final output dimension

### ISSUE THREAD

**Issue by likojack** [chrischoy/3D-R2N2#7]
Hi,

I found out in your code and your paper as well that the final output of the network is [batch_size, n_vox, 2, n_vox, n_vox]. Why would you need 2 output channel?

Cheers

**Comment by chrischoy** [comment]
The network is producing voxel-wise occupancy probabilities. 0 for empty and 1 for occupied.

**Comment by likojack** [comment]
Alright, but isn't probability of empty the complement of probability of occupied?

**Comment by hzxie** [comment]
I have the same question. What are the 2 output channels used for?
